// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8V3N0fGjdRwBx1Z2RNI0dCcqk6EGn5ZU',
    appId: '1:294581290614:web:93f1d4cb78e7960eaa4157',
    messagingSenderId: '294581290614',
    projectId: 'fir-crud-basics-e3476',
    authDomain: 'fir-crud-basics-e3476.firebaseapp.com',
    storageBucket: 'fir-crud-basics-e3476.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqomHLvGZQEfgOfnTBCgssfHXlDG2IIcU',
    appId: '1:294581290614:android:8a6e7a1bb6720325aa4157',
    messagingSenderId: '294581290614',
    projectId: 'fir-crud-basics-e3476',
    storageBucket: 'fir-crud-basics-e3476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIrrabgeLg_LGGzT3n2QUR6ISy-FqTQBs',
    appId: '1:294581290614:ios:135e91c3126ffda0aa4157',
    messagingSenderId: '294581290614',
    projectId: 'fir-crud-basics-e3476',
    storageBucket: 'fir-crud-basics-e3476.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIrrabgeLg_LGGzT3n2QUR6ISy-FqTQBs',
    appId: '1:294581290614:ios:135e91c3126ffda0aa4157',
    messagingSenderId: '294581290614',
    projectId: 'fir-crud-basics-e3476',
    storageBucket: 'fir-crud-basics-e3476.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8V3N0fGjdRwBx1Z2RNI0dCcqk6EGn5ZU',
    appId: '1:294581290614:web:93ed7d20d23e7e3caa4157',
    messagingSenderId: '294581290614',
    projectId: 'fir-crud-basics-e3476',
    authDomain: 'fir-crud-basics-e3476.firebaseapp.com',
    storageBucket: 'fir-crud-basics-e3476.firebasestorage.app',
  );

}